### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by yanrising** [script-money/ens-claim-flashbot-example#2]
Hi! Its my scriptkiddy error or something wrong?
Last version of node js - with command yarn all dependencies install correctly 
λ yarn start
yarn run v1.22.17
$ ts-node --project tsconfig.json src/index.ts
[2021-12-29T14:14:28.736Z] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at GAS.getSponsoredTransactions (c:\****\src\engine\GAS.ts:83:37)
    at main (c:\Airdrop\src\index.ts:95:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at run (c:\Airdrop\src\index.ts:167:7)

P.S. Thank you for your scripts. They developed my desire to study nodejs and solidity.

**Comment by yanrising** [comment]
Maybe this help? [https://github.com/X01M/gasdao](url)

**Comment by script-money** [comment]
You have to replace 78 with your merkle proof json, detail in comment

**Comment by yanrising** [comment]
All understood - thank you!
